
const Questions = ([
    {question: "The only letter not in the periodic table is the letter _______.", answer: "J", placebo1: "Q", placebo2: "V", placebo3: "P", placebo4: "S", placebo5: "W"},
    {question: "When burning, lithium gives off a bright this color flame.", answer: "Red", placebo1: "Blue", placebo2: "Green", placebo3: "Yellow", placebo4: "Orange", placebo5: "Grey"},
    {question: "White tin will transform into this color tin when the temperature falls below 13.2 degrees C.", answer: "Grey", placebo1: "Golden", placebo2: "Yellow", placebo3: "Rust", placebo4: "Auburn", placebo5: "Turquoise"},
    {question: "As a gas, iodine is a vapor that is this color.", answer: "Purple", placebo1: "Smoke", placebo2: "White", placebo3: "Yellow", placebo4: "Red", placebo5: "None"},
    {question: "The country Argentina is named after this element. It would be easy to guess if you saw it written in Latin.", answer: "Ag", placebo1: "Ts", placebo2: "Zn", placebo3: "As", placebo4: "He", placebo5: "K"},
    {question: "The rows of the Periodic Table are called this.", answer: "Periods", placebo1: "Areas", placebo2: "Zones", placebo3: "Series", placebo4: "Groups", placebo5: "Majors"}, 
    {question: "The columns of the Periodic Table are called this.", answer: "Groups", placebo1: "Minors", placebo2: "Zones", placebo3: "Ranks", placebo4: "Models", placebo5: "Tracks"},
    {question: "In the mid-1800s this metal was more expensive than gold.", answer: "Aluminum", placebo1: "Magnesium", placebo2: "Radium", placebo3: "Neon", placebo4: "Silver", placebo5: "Krypton"},
    {question: "Though generally not found in its free form, it is the most stable isotope of all the elements.", answer: "Tin", placebo1: "Copper", placebo2: "Calcium", placebo3: "Hydrogen", placebo4: "Helium", placebo5: "Titanium"},
    {question: "Its' plain to see. For years, this element was called 'plumbum nigrum'. Tin was called 'plumbum album' because it was thought they were the same metal.", answer: "Lead", placebo1: "Bronze", placebo2: "Copper", placebo3: "Iron", placebo4: "Osmium", placebo5: "Tungsten"},
    {question: "It is the most naturally magnetic of the elements.", answer: "Iron", placebo1: "Oxygen", placebo2: "Hydrogen", placebo3: "Nickel", placebo4: "Carbon", placebo5: "Calcium"},
    {question: "This Element gets its name from the Greek word 'iodes' which means 'violet.'", answer: "Iodine", placebo1: "Phosphorus", placebo2: "Boron", placebo3: "Argon", placebo4: "Lead", placebo5: "Iridium"},
    {question: "Some of the best sources our body has for this element are dairy products, salmon, and tofu.", answer: "Calcium", placebo1: "Potassium", placebo2: "Oxygen", placebo3: "Sodium", placebo4: "Sulfur", placebo5: "Arsenic"},
    {question: "Brands like Pyrex and Duran use this element when producing their high end cookware.", answer: "Boron", placebo1: "Silicon", placebo2: "Zinc", placebo3: "Bromine", placebo4: "Carbon", placebo5: "Xenon"},
    {question: "Brrr!  This is the only element will remain a liquid even at absolute zero.", answer: "Helium", placebo1: "Nitrogen", placebo2: "Silicon", placebo3: "Silver", placebo4: "Tennessine", placebo5: "Neon"},
    // {question: "", answer: "", placebo1: "", placebo2: "", placebo3: "", placebo4: "", placebo5: ""},
    // {question: "", answer: "", placebo1: "", placebo2: "", placebo3: "", placebo4: "", placebo5: ""},
    // {question: "", answer: "", placebo1: "", placebo2: "", placebo3: "", placebo4: "", placebo5: ""},
    // {question: "", answer: "", placebo1: "", placebo2: "", placebo3: "", placebo4: "", placebo5: ""},
    // {question: "", answer: "", placebo1: "", placebo2: "", placebo3: "", placebo4: "", placebo5: ""},
    // {question: "", answer: "", placebo1: "", placebo2: "", placebo3: "", placebo4: "", placebo5: ""},
    // {question: "", answer: "", placebo1: "", placebo2: "", placebo3: "", placebo4: "", placebo5: ""},
    // {question: "", answer: "", placebo1: "", placebo2: "", placebo3: "", placebo4: "", placebo5: ""},
    // {question: "", answer: "", placebo1: "", placebo2: "", placebo3: "", placebo4: "", placebo5: ""},
    // {question: "", answer: "", placebo1: "", placebo2: "", placebo3: "", placebo4: "", placebo5: ""},
    // {question: "", answer: "", placebo1: "", placebo2: "", placebo3: "", placebo4: "", placebo5: ""},
    // {question: "", answer: "", placebo1: "", placebo2: "", placebo3: "", placebo4: "", placebo5: ""},
    // {question: "", answer: "", placebo1: "", placebo2: "", placebo3: "", placebo4: "", placebo5: ""},
    // {question: "", answer: "", placebo1: "", placebo2: "", placebo3: "", placebo4: "", placebo5: ""},
    // {question: "", answer: "", placebo1: "", placebo2: "", placebo3: "", placebo4: "", placebo5: ""},
    // {question: "", answer: "", placebo1: "", placebo2: "", placebo3: "", placebo4: "", placebo5: ""},

])

 export default Questions;